//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PraktikaEntities2 : DbContext
    {
        public PraktikaEntities2()
            : base("name=PraktikaEntities2")
        {
        }

        private static PraktikaEntities2 _context;

        public static PraktikaEntities2 GetContext()
        {



            if (_context == null)
                _context = new PraktikaEntities2();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Анализ_ВТД> Анализ_ВТД { get; set; }
        public virtual DbSet<ВПД> ВПД { get; set; }
        public virtual DbSet<Вывоз_угля> Вывоз_угля { get; set; }
        public virtual DbSet<Грузополучатель> Грузополучатель { get; set; }
        public virtual DbSet<Декларация> Декларация { get; set; }
        public virtual DbSet<Качество> Качество { get; set; }
        public virtual DbSet<КоличествоТоннОтгруженоПоНакладной> КоличествоТоннОтгруженоПоНакладной { get; set; }
        public virtual DbSet<КолТоннПоВТД> КолТоннПоВТД { get; set; }
        public virtual DbSet<КонтрАгент> КонтрАгент { get; set; }
        public virtual DbSet<МаркаУгля> МаркаУгля { get; set; }
        public virtual DbSet<Месяц> Месяц { get; set; }
        public virtual DbSet<Месяц1> Месяц1 { get; set; }
        public virtual DbSet<Накладная> Накладная { get; set; }
        public virtual DbSet<НаКолесах> НаКолесах { get; set; }
        public virtual DbSet<Остатки_на_складе> Остатки_на_складе { get; set; }
        public virtual DbSet<ОстатокПоВТДд> ОстатокПоВТДд { get; set; }
        public virtual DbSet<Отправитель> Отправитель { get; set; }
        public virtual DbSet<Отчет_по_складам> Отчет_по_складам { get; set; }
        public virtual DbSet<Подразделения> Подразделения { get; set; }
        public virtual DbSet<Приходование_материалов> Приходование_материалов { get; set; }
        public virtual DbSet<Професия> Професия { get; set; }
        public virtual DbSet<Работники> Работники { get; set; }
        public virtual DbSet<Реестр> Реестр { get; set; }
        public virtual DbSet<Самовывоз> Самовывоз { get; set; }
        public virtual DbSet<СправДек> СправДек { get; set; }
        public virtual DbSet<СправкаВТД> СправкаВТД { get; set; }
        public virtual DbSet<Станция> Станция { get; set; }
        public virtual DbSet<Станция2> Станция2 { get; set; }
        public virtual DbSet<СтанцияОтправления> СтанцияОтправления { get; set; }
        public virtual DbSet<Страна> Страна { get; set; }
        public virtual DbSet<Страна1> Страна1 { get; set; }
        public virtual DbSet<Страна2> Страна2 { get; set; }
        public virtual DbSet<Страны> Страны { get; set; }
        public virtual DbSet<Участки> Участки { get; set; }
    }
}
