//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Анализ_ВТД
    {
        public int Id_АнализВТД { get; set; }
        public int Id_Месяц { get; set; }
        public Nullable<int> Id_ВТД { get; set; }
        public Nullable<int> Id_КолвоТоннПоВТД { get; set; }
        public Nullable<int> КоличествоТоннОтгруженоПоНакладнойй { get; set; }
        public string ОстатокПоВТД { get; set; }
    
        public virtual КоличествоТоннОтгруженоПоНакладной КоличествоТоннОтгруженоПоНакладной { get; set; }
        public virtual КолТоннПоВТД КолТоннПоВТД { get; set; }
        public virtual Месяц Месяц { get; set; }
        public virtual СправДек СправДек { get; set; }
    }
}
