//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ВПД
    {
        public int Id_ВПД { get; set; }
        public Nullable<int> Id_Месяц3 { get; set; }
        public Nullable<int> Id_АнализВТДд { get; set; }
        public Nullable<int> Id_ВТД { get; set; }
        public Nullable<int> Id_КолВоПоВТД { get; set; }
        public string ПТДномер { get; set; }
        public Nullable<int> КолВоТоннОтгруз { get; set; }
        public string КолПоПТДзакрыто { get; set; }
        public int СтранаПоПТД { get; set; }
    
        public virtual КоличествоТоннОтгруженоПоНакладной КоличествоТоннОтгруженоПоНакладной { get; set; }
        public virtual КолТоннПоВТД КолТоннПоВТД { get; set; }
        public virtual Месяц1 Месяц1 { get; set; }
        public virtual СправДек СправДек { get; set; }
        public virtual Страны Страны { get; set; }
    }
}
