//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Вывоз_угля
    {
        public int Id_ВывозУгля { get; set; }
        public int Самовывоз { get; set; }
        public int Сотрудник { get; set; }
        public string Должность { get; set; }
        public System.DateTime ДатаПриема { get; set; }
        public int Грузополучатель { get; set; }
    
        public virtual Грузополучатель Грузополучатель1 { get; set; }
        public virtual Професия Професия { get; set; }
        public virtual Работники Работники { get; set; }
        public virtual Самовывоз Самовывоз1 { get; set; }
    }
}
