//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom2
{
    using System;
    using System.Collections.Generic;
    
    public partial class НаКолесах
    {
        public int Id_СкладНаКолесах { get; set; }
        public Nullable<int> Склад { get; set; }
        public string НачальныйОстаток { get; set; }
        public string Приход { get; set; }
        public string Расход { get; set; }
        public string КонечныйОстаток { get; set; }
    }
}
