//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Приходование_материалов
    {
        public int Id_ПриходованиеМатериала { get; set; }
        public string Дата { get; set; }
        public string Номер { get; set; }
        public string Сумма { get; set; }
        public string Склад { get; set; }
        public string Организация { get; set; }
    }
}
