//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Професия
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Професия()
        {
            this.Вывоз_угля = new HashSet<Вывоз_угля>();
        }
    
        public int Id_Профессий { get; set; }
        public string Наименование { get; set; }
        public Nullable<int> Id_Участок { get; set; }
        public string Должность { get; set; }
        public string Оклад { get; set; }
        public string Статус { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Вывоз_угля> Вывоз_угля { get; set; }
        public virtual Участки Участки { get; set; }
    }
}
