//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Реестр
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Реестр()
        {
            this.Декларация = new HashSet<Декларация>();
        }
    
        public int Id_Реестр { get; set; }
        public string СоставНетто { get; set; }
        public string СоставГрузоподьемности { get; set; }
        public int КачествоТовара { get; set; }
        public string СрокДоставки { get; set; }
        public string Дата { get; set; }
        public string КолПВ { get; set; }
        public string КолТонн { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Декларация> Декларация { get; set; }
        public virtual Качество Качество { get; set; }
    }
}
